version: '2.2'
services:
  oracle-db:
    image: container-registry.oracle.com/database/free:latest
    container_name: oracle-demo
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PWD=123
    volumes:
      - oracle-data:/opt/oracle/oradata # Path for persistent data
      - ./data-to-import:/dir01
volumes:
  oracle-data:
